service: jText

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  timeout: 4
  environment:
    MAIL_DOT_COM_EMAIL: ${ssm:/jText_mailDotCom_email}
    MAIL_DOT_COM_PW: ${ssm:/jText_mailDotCom_pw}
    PHONE_EMAIL: ${ssm:/jText_phone_email}

functions:
  jText:
    handler: handler.jText
    events:
      - schedule: cron(* 9,12,18 * * *)